import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { Card, CardContainer, SearchInput } from '../components'
import { useState } from 'react'
import axios from 'axios'
import { useSearchContext } from '../context/useSearchContext'

interface Props {
  cards: Card[]
}

const Home: NextPage<Props> = ({ cards }) => {
  const [favourites, setFavourites] = useState<any>(cards)

  const { searchedData, handleSearchedFavourites } = useSearchContext()

  const handleFavourite = (id: string) => {
    setFavourites((prevFavourites: Card[]) => (
      prevFavourites.map(card => ({
        ...card,
        isFavourite: card.id === id 
          ? !card.isFavourite 
          : card.isFavourite
      }))
    ))
  }

  const renderCards = favourites.map((card: Card) => (
    <Card 
      key={card.id}
      id={card.id}
      image={card.image}
      isFavourite={card.isFavourite}
      handleFavourite={() => handleFavourite(card.id)}
    />
  ))

  const renderSearchedCards = searchedData.map((card: Card) => (
    <Card
      key={card.id}
      id={card.id}
      image={card.image}
      isFavourite={card.isFavourite}
      handleFavourite={() => handleSearchedFavourites(card.id)}
    />
  ))



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='main'>
        <SearchInput />
        <CardContainer>
          {
            searchedData.length > 0
              ? renderSearchedCards
              : renderCards
          }
        </CardContainer>
      </main>

    </>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const { data } = await axios.get('https://api.giphy.com/v1/gifs/trending?api_key=HC5YScnd2Kws9G5xAgZFUAC0XGj16Xse')

  const cards: Card[] = data.data.map((card: any) => ({
    id: card.id,
    image: card.images.original.url,
    isFavourite: false
  }))

  return {
    props: {cards},
  }
}

export default Home
