import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { Card, CardContainer, SearchInput } from '../components'
import { useMemo, useState } from 'react'
import { useSearchContext } from '../context/useSearchContext'
import { getTrendingGifs } from '../service'

interface Props {
  cards: Card[]
}

const Home: NextPage<Props> = ({ cards }) => {
  const [favourites, setFavourites] = useState<any>(cards)

  const { searchedData, handleSearchedFavourites } = useSearchContext()

  const handleFavourite = (id: string) => {
    setFavourites((prevFavourites: Card[]) => (
      prevFavourites.map(card => ({
        ...card,
        isFavourite: card.id === id 
          ? !card.isFavourite 
          : card.isFavourite
      }))
    ))
  }

  const renderCards = useMemo(() =>(
    favourites.map((card: Card) => (
      <Card 
        key={card.id}
        id={card.id}
        image={card.image}
        isFavourite={card.isFavourite}
        handleFavourite={() => handleFavourite(card.id)}
      />
    ))
  ), [favourites])

  const renderSearchedCards = useMemo(()=>(
    searchedData.map((card: Card) => (
      <Card
        key={card.id}
        id={card.id}
        image={card.image}
        isFavourite={card.isFavourite}
        handleFavourite={() => handleSearchedFavourites(card.id)}
      />
    ))
  ), [searchedData]) 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='main'>
        <SearchInput />
        <CardContainer>
          {
            searchedData.length > 0
              ? renderSearchedCards
              : renderCards
          }
        </CardContainer>
      </main>

    </>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const { data } = await getTrendingGifs()

  const cards: Card[] = data.map((card: any) => ({
    id: card.id,
    image: card.images.original.url,
    isFavourite: false
  }))

  return {
    props: {cards},
  }
}

export default Home
